spring:
  application:
    name:clone

  datasource:
    url: jdbc:mysql://localhost:3306/velog
    username: root
    password: heejin2
    driver-class-name: com.mysql.cj.jdbc.Driver


    #    jpa:
    #      hibernate:
    #        ddl-auto: update
    #      show-sql: true
    #
    #      properties:
    #        hibernate:
    #          format_sql:true

    jpa:
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


file:
  dir: /Users/heejin/Desktop/portfolio/velog/src/main/resources/files/

server:
  tomcat:
    uri-encoding: UTF-8
    use-relative-redirects: true